### PR TITLE
Checkbox / toolbar issue

### PR DESCRIPTION
**Pull request by allanpilarca**
Fix checkbox toolbar issue

### CODE REVIEW

**Comment by johanjanssens** [comment]
@robinpoort Could you test the fix for this issue?

**Comment by robinpoort** [comment]
@allanpilarca 

Selecting the top checkbox still doesn't work?

checkbox

**Comment by allanpilarca** [comment]
@robinpoort 

Havent noticed that checkall button since i focus on the caret and edit functionality :), Seems this is also related to `Footable` and `floatThead` issue. All the links in the header is not clickable when its enabled. Will check how to fix it.

**Comment by allanpilarca** [comment]
@robinpoort the problem here is the tooltip and the floatThead script are having conflict. When the element has a tooltip inside the table header that element became unclickable. Still looking for a solution here.

**Comment by robinpoort** [comment]
@allanpilarca I guess I've got great news for you then! We're not using floatthead anymore in the latest version of Joomlatools UI:

https://www.joomlatools.xxx/blog/2017/07/joomlatools-ui-v010-released/

https://github.com/timble/kodekit-ui/blob/master/src/scss/admin/molecules/_table.scss#L188-L192

All you'd have to do is update to the latest Joomlatools UI. If you don't feel comfortable doing that let me know and I'll take care of it.

**Comment by allanpilarca** [comment]
@robinpoort so updating the joomlatools UI will fix it. I think its better if you handle it. Thank you :)

**Comment by robinpoort** [comment]
@allanpilarca Not sure if the issue itself will be fixed but at least floatThead won't be in the way anymore

**Comment by robinpoort** [comment]
BTW: this will have to wait until the new platform template is done. Can't just update the UI in here. So for now this PR is good I'd say.

**Comment by allanpilarca** [comment]
Ok then, I think it will fix it since the floatthead is having conflict in element with tooltip, its not the checkboxall only but every element like the title for sorting in the header. 

Seems we can merge this one?

**Comment by robinpoort** [comment]
Yes I think we can!

**Comment by johanjanssens** [comment]
Good work guys!

**Pull request merged**
